### PR TITLE
 #164393459 Add a pull request template to the GitHub repository

### PR DESCRIPTION
**Pull request by davidshare**
#### What does this PR do?
- add a pull request template to the GitHub repository
#### Description of Task to be completed?
- create a PULL_REQUEST_TEMPLATE.md file containing the template for pull requests
#### How should this be manually tested?
- create a branch locally
- implement a feature or chore
- push to the remote repository
- try to create a pull request
- you should see the template in your pull request box
#### Any background context you want to provide?
- none
#### What are the relevant pivotal tracker stories?
 [#164393459](https://www.pivotaltracker.com/story/show/164393424)
#### Screenshots (if appropriate)
- none
#### Questions:
- none

### CODE REVIEW

**Comment by pmndifon** [comment]
This works well. Is this template going to be automatically created on a pull request?

**Comment by davidshare** [comment]
> This works well. Is this template going to be automatically created on a pull request?

yes, it will

**Comment by davidshare** [comment]
Please the pull request cannot be merged until two people review and approve, please, review and approve.

**Review by pmndifon — APPROVED** [review]
It's fine. Merge it.

**Review by Danielshow — APPROVED** [review]
Nice job @davidshare, LGTM

**Pull request merged**
